general {
    after_sleep_cmd = sleep 1 && omarchy-system-wake                 # delay for PAM readiness, then turn on display.
}

# Start screensaver after 5 minutes
listener {
    timeout = 600
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}
